version: 2
jobs:
  build:
    docker:
      - image: docker:17.07.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Prepare suitable tag name
          command: |
            if [ "$CIRCLE_TAG" ]; then
              DOCKER_TAG="$CIRCLE_TAG"
            else
              DOCKER_TAG=$(echo "$CIRCLE_BRANCH" | sed 's/[^[:alnum:]._-]/_/g' | sed -e 's/^master$/latest/')
            fi
            echo "export DOCKER_TAG=$DOCKER_TAG" | tee docker_tag
      - run:
          name: Build image
          command: |
            source docker_tag
            # Replace with your repository name
            docker build -t relastle/pmy:${DOCKER_TAG} -f ./docker/Dockerfile .
      - run:
          name: Push
          command: |
            source docker_tag
            # Replace with your repository name
            docker push relastle/pmy:${DOCKER_TAG}
  test:
    docker:
      - image: relastle/pmy:${DOCKER_TAG}
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: integration_test
          command: zsh ./test.zsh
workflows:
  test-workflow:
    test:
      requires:
        - build

